# Generated by Django 4.2.16 on 2025-01-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twofa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
