# Generated by Django 4.2.16 on 2025-01-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_otp_expiry_alter_user_otp_base32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(default='2EUJRP4LAE7OQWIB43C2CTC6UZ34PG7N', max_length=32),
        ),
    ]
