# Generated by Django 4.2.16 on 2025-01-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_twofa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coverImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='offline', max_length=20),
        ),
    ]
