# Generated by Django 4.2.16 on 2025-01-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_otp_base32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(default='UH5SAWBGNKF5IDRIHMWU2CMJQQ2QAWEV', max_length=32),
        ),
    ]
