# Generated by Django 4.2.16 on 2025-01-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_coverimage_user_level_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
