# Generated by Django 4.2.16 on 2025-01-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_otp_base32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(default='U3UNPKB44JSF26SQX35CPLD27YAG245K', max_length=32),
        ),
    ]
