# Generated by Django 4.2.16 on 2025-01-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_otp_secret_user_login_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_otp_used',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(default='EZE7WOQ7W3YAVVSWRMFBDYWZBDDQF7S4', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
