# Generated by Django 4.2.16 on 2025-01-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_otp_base32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(default='WZD2PHAQACWYTJDVS2SXU7O4YQSW3A5S', max_length=32),
        ),
    ]
