# Generated by Django 4.2.16 on 2025-01-03 03:10

from django.db import migrations, models
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_user_otp_base32"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="otp_expiry",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otpauth_url",
        ),
        migrations.AlterField(
            model_name="user",
            name="otp_base32",
            field=models.CharField(default=pyotp.random_base32, max_length=32),
        ),
    ]
