# Generated by Django 4.2.16 on 2025-01-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_login_otp_remove_user_login_otp_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(default='4FNLGGM76HDRDIPJLEUU2R2SMBJL2WMI', max_length=32),
        ),
    ]
