version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:latest
    env_file:
      - backend/.env/db.env
    ports:
      - "5432:5432"
    networks:
      - trancendance-network
    healthcheck:
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 10s
        timeout: 5s
        retries: 5
#////////////////////////////////////////////////////////////////
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      postgres-database:
        condition: service_healthy
    networks:
      - trancendance-network
#////////////////////////////////////////////////////////////////
  frontend:
    container_name: frontend
    build:
      context: ./fron-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./fron-end:/app
    depends_on:
      - backend
      - db
    networks:
      - trancendance-network
#////////////////////////////////////////////////////////////////
networks:
  default:
    external:
      name: my-network