version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - /goinfre/asabri/ft-trancendance/backend:/app
    depends_on:
      - db
    networks:
      - trancendance-network
#////////////////////////////////////////////////////////////////
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trancendance-network
#////////////////////////////////////////////////////////////////
  
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     # dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /goinfre/asabri/ft-trancendance/fron-end:/frontend
  #   # depends_on:
  #   #   - backend
  #   #   - db
  #   networks:
  #     - trancendance-network
#////////////////////////////////////////////////////////////////
networks:
  trancendance-network:
    name: trancendance-network

volumes:
  postgres_data: