version: '3.8'
services:
  # db:
  #   container_name: postgres
  #   image: postgres:latest
  #   env_file:
  #     - backend/.env/db.env
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - trancendance-network
  #   healthcheck:
  #     healthcheck:
  #       test: ["CMD-SHELL", "pg_isready"]
  #       interval: 10s
  #       timeout: 5s
  #       retries: 5 
#////////////////////////////////////////////////////////////////
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /goinfre/asabri/ft-trancendance/backend:/usr/src/app
    # depends_on:
    #   db:
    #     condition: service_healthy
    networks:
      - trancendance-network
#////////////////////////////////////////////////////////////////
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     # dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /goinfre/asabri/ft-trancendance/fron-end:/frontend
  #   # depends_on:
  #   #   - backend
  #   #   - db
  #   networks:
  #     - trancendance-network
#////////////////////////////////////////////////////////////////
networks:
  trancendance-network:
    name: trancendance-network