FROM python:3.9.5

WORKDIR /backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update 
COPY requirements.txt .
RUN python -m venv venv
RUN . venv/bin/activate
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

RUN chmod +x run.sh
CMD ["bash", "run.sh"]