FROM python:3.9.5

WORKDIR /app


COPY requirements.txt .
RUN python -m venv venv
RUN . venv/bin/activate
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "app/manage.py", "runserver"]